export const Users = [
  {
    id:1,
    profilePicture: "assets/person/2.jpeg",
    username: "Yuliia Blahovistna",
  },
  {
    id:2,
    profilePicture: "assets/person/3.jpeg",
    username: "Yelyzaveta Vikarii",
  },
  {
    id:3,
    profilePicture: "assets/person/4.jpeg",
    username: "Yuliia Bahlai",
  },
  {
    id:4,
    profilePicture: "assets/person/5.jpeg",
    username: "Kateryna Bestanchuk",
  },
  {
    id:5,
    profilePicture: "assets/person/6.jpeg",
    username: "Yuliia Mustafina",
  },
  {
    id:6,
    profilePicture: "assets/person/7.jpeg",
    username: "Yevgeniya Petrenko",
  },
  {
    id:7,
    profilePicture: "assets/person/8.jpeg",
    username: "Oksana Torina",
  },
  {
    id:8,
    profilePicture: "assets/person/9.jpeg",
    username: "Maryna Astapeieva",
  },
  {
    id:9,
    profilePicture: "assets/person/10.jpeg",
    username: "Yelyzaveta Dmytrenko",
  },
  {
    id:10,
    profilePicture: "assets/person/11.jpeg",
    username: "Antonina Shcherbakova",
  },
  {
    id:11,
    profilePicture: "assets/person/2.jpeg",
    username: "Anna Parkhomenko",
  },
  {
    id:12,
    profilePicture: "assets/person/12.jpeg",
    username: "Liudmyla Shatova",
  },
  {
    id:13,
    profilePicture: "assets/person/13.jpeg",
    username: "Anna Bohutska",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "My delicious dinner!",
    photo: "assets/post/5.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Me too)",
    photo: "assets/post/2.jpeg",
    date: "11 mins ago",
    userId: 2,
    like: 19,
    comment: 6,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/10.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "The weak can never forgive. Forgiveness is the attribute of the strong.",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Success is the ability to go from failure to failure without losing your enthusiasm.",
    photo: "assets/post/1.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Wise men speak because they have something to say; fools because they have to say something.",
    photo: "assets/post/8.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 10,
    comment: 4,
  },
  {
    id: 11,
    photo: "assets/post/11.jpeg",
    date: "1 week ago",
    userId: 11,
    like: 29,
    comment: 19,
  },
  {
    id: 12,
    desc: "When you do something noble and beautiful and nobody noticed, In the End, we will remember not the words of our enemies, but the silence of our friends. not be sad.",
    photo: "assets/post/12.jpeg",
    date: "1 week ago",
    userId: 12,
    like: 104,
    comment: 12,
  },
  {
    id: 13,
    desc: "Haaaaandsome",
    photo: "assets/post/13.jpeg",
    date: "1 week ago",
    userId: 13,
    like: 29,
    comment: 19,
  },
];